Test-task. Stage 2
art-ch/imaginary-real-estate-agency pull request #1
Opened 2022-02-10 13:36 UTC by art-ch

**Short summary of commits included:**

1. React Router
2. Redux by ducks method. Redux Saga.
3. Fixed double rerender of House component. Fixed UI for large screen

2022-02-10 18:22 UTC, mike-gusiev requested changes

2022-02-10 18:22 UTC, mike-gusiev commented on README.md
> +
- зроби спінер по центру сторінки
- добав кнопку "назад" на сторінку будинку

2022-02-10 18:22 UTC, mike-gusiev commented on src/App.js
>    return (
використовуй коротку форму es6 функцій без return, там де це можливо

2022-02-10 18:22 UTC, mike-gusiev commented on src/App.js
> +import House from './components/House';
в папці src/components створи файл index.js. щоб всі компоненти можна було імпортувати одним рядком

2022-02-10 18:22 UTC, mike-gusiev commented on src/api.js
> +    const response = await fetch('https://demo0733949.mockable.io/houses');
винеси префікс урла в константи

2022-02-10 18:22 UTC, mike-gusiev commented on src/api.js
> +      const newRealEstate = houses.map((house) => {
винеси маніпуляції з данними в окрему функцію

2022-02-10 18:22 UTC, mike-gusiev commented on src/components/HomePage.js
> +import { Card, Container, Row, Col, Button, Spinner } from 'react-bootstrap';
погрупуй імпорти. спочатку будуть іти імпорти бібліотек, потім відступ, потім імпорти компонентів, потім відступ, потім імпорт всього іншого

2022-02-10 18:22 UTC, mike-gusiev commented on src/redux/sagas/handlers/house.js
> +import { call, put } from 'redux-saga/effects';
структура редаксу трохи неправильна. позбудься папки sagas. і в папку src/redux/ducks в файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2022-02-10 18:22 UTC, mike-gusiev commented on src/styled/GlobalStyles.js
> +  @media (min-width: 767px) {
створи файл для глобальних змінних styled components. і туди повиносили всі кольори і розміри в медіа запитах

2022-02-11 06:11 UTC, art-ch commented on src/components/HomePage.js
> +import { Card, Container, Row, Col, Button, Spinner } from 'react-bootstrap';
Я перегрупував імпорти.
Подивіться, будь-ласка, чи я правильно зрозумів дане зауваження

![regrouped-imports-1-1](https://user-images.githubusercontent.com/78142286/153544866-8bb9cfeb-ad99-4c2f-ac19-1ec6ca21f300.png)
![regrouped-imports-1-2](https://user-images.githubusercontent.com/78142286/153544867-596d3822-9e3d-4de6-ae79-0ce20bf085f5.png)

2022-02-11 11:10 UTC, merged