New exciting features
art-ch/imaginary-real-estate-agency pull request #3
Opened 2022-02-14 14:24 UTC by art-ch

2022-02-15 08:57 UTC, mike-gusiev requested changes

2022-02-15 08:57 UTC, mike-gusiev commented on src/utils.js
> +export const mediaCreator = () => {
просто створи окремий файл styled components зі змінними які тобі потрібні:
https://take.ms/NMj0c

2022-02-16 10:37 UTC, mike-gusiev requested changes

2022-02-16 10:37 UTC, mike-gusiev commented on src/components/HomePage.tsx
> +    (state: any) => state.getRealEstateReducer.realEstate
позбудься any. не повині бути непокриті типами частини коду

2022-02-16 10:37 UTC, mike-gusiev commented on tsconfig.json
> +}
перед відправкою пул реквеста на рев'ю переглядай файли свого пул реквесту на гітхабі. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2022-02-16 10:44 UTC, art-ch commented on tsconfig.json
> +}
Зрозумів. Виправив налаштування vscode

2022-02-22 22:12 UTC, mike-gusiev requested changes

2022-02-22 22:12 UTC, mike-gusiev commented on .env
>  # hot reload fix
не хоче працювати програма:
https://take.ms/Zpwya

2022-02-22 22:12 UTC, mike-gusiev commented on src/App.test.tsx
> +import renderer from 'react-test-renderer';
створи папку src/tests. і туди попереміщуй все що стосується тестів

2022-02-22 22:12 UTC, mike-gusiev commented on src/App.test.tsx
> +test('App is rendered without crashing', () => {
кожен тест it повинен починатися зі слова should. і мати якесь осмисленне речення. наприклад:

it should match a snapshot

2022-02-22 22:12 UTC, mike-gusiev commented on src/api.test.ts
> +  rest.get('https://demo0733949.mockable.io/houses', (req, res, ctx) => {
url бери з констант

2022-02-22 22:12 UTC, mike-gusiev commented on src/components/HomePage.tsx
> +import { HouseSchema } from '../interfaces';
одним імпортом це імпорть

2022-02-22 22:12 UTC, mike-gusiev commented on src/redux/ducks/getHouse.test.ts
> +    expect(generator.next().value).toEqual(call(fetchHouse, id));
на кожен expect має бути окремий тест it

2022-03-08 09:34 UTC, merged